// Generated by CodiumAI

const uniswap = require("./uniswap");

describe('uniswap', () => {
    // beforeAll(() => jest.setTimeout(30000))

    // Successfully fetches token data
    it('should successfully fetch token data', async () => {
        const amount = await uniswap();
        // console.log(amount);
        expect(amount.pair).toEqual('waxpeth');
        expect(amount.value).toBeGreaterThan(0);
    }, 10000);
});
